### ISSUE TITLE
Let's go to Lasertag tonight 😁

### ISSUE THREAD

**Issue by Sajjad-Arjmand** [amirsarfar/dyna-cms-base#2]
Hey Amir!
are you OK with the plan for tonight ?

**Comment by amirsarfar** [comment]
> Hey Amir!
> are you OK with the plan for tonight ?

یه زنگی باید بزنم به خونه

**Comment by Sajjad-Arjmand** [comment]
بزن دایی. خبرشو کامنت کن 😂

**Comment by Sajjad-Arjmand** [comment]
> > Hey Amir!
> > are you OK with the plan for tonight ?
> 
> یه زنگی باید بزنم به خونه

بزن دایی. خبرشو کامنت کن 😂
